[[data]]
name = "空地"
label = "."

[data.passing]
left = true
right = true
top = true
down = true

[[data]]
name = "树木"
label = "Y"

[data.passing]
left = false
right = false
top = false
down = false

[[data]]
name = "墙"
label = "│"

[data.passing]
left = false
right = false
top = false
down = false

[[data]]
name = "墙"
label = "─"

[data.passing]
left = false
right = false
top = false
down = false
